name: coil
version: '1.3.9'
summary: User friendly CMS for Nikola
description: |
  Coil provides a web-based interface for the administration of a static
  site built using Nikola.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict

apps:
   coil:
      command: bin/coil
      plugs: [network-bind, network]
   rqworker:
      command: bin/rqworker
      plugs: [network-bind, network]
   rqinfo:
      command: bin/rqinfo
      plugs: [network]
   gunicorn:
      command: bin/gunicorn
      plugs: [network-bind]

parts:
   coil:
    # See 'snapcraft plugins'
    plugin: python
    python-version: python2
    source: git@github.com:getnikola/coil.git
    source-tag: v1.3.9
    build-packages:
      - python3-dev
    python-packages:
      - gunicorn
      - rq
    stage-packages:
      - locales
      - libc-bin
